language: d
sudo: false
dist: trusty

before_install:
  - pip3 install meson>=0.40

install:
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
 - export PATH=$PATH:$PWD/.ntmp

script:
  - dub test --compiler=${DC}
  - dub run --root=test --compiler=${DC}
  - mkdir build && cd build
  - meson ..
  - ninja && ninja test
  - DESTDIR=/tmp/target/ ninja install
